DataDog/opentelemetry-mapping-go

.chloggen/mx-psi_backport-count-greater-than-bins.yaml, pkg/quantile/sparse.go, pkg/quantile/sparse_test.go
Backports fix to Quantile method when the count is greater than the sum of the bins (DataDog/dd-go@f457099e9071709785f5cd4982cd6530c8931468). This can happen after conversion from other formats (such as ExponentialHistograms!) because of rounding/floating-point errors.
Consistency with internal version of this module.
=> [pkg/quantile] Backport fix for 'count greater than sum of bins' edge case

pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Adds code in OTLP metrics translator to map OTel runtime metrics to Datadog runtime metrics. If a mapping is found for an incoming runtime metric, both the original OTel runtime metric and the equivalent Datadog runtime metric will be sent to the backend. Runtime metric mappings are implemented for Go in a separate file containing a Go struct.
=> Add support for Go runtime metrics

pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Adds mappings for .NET runtime metrics and adds mapping code to handle metrics with attributes that need to be mapped to Datadog runtime metrics. In order to do this, I refactored how we store runtime metric mappings to support this nested data structure.
For example, the OTel runtime metric `process.runtime.dotnet.gc.collections.count` has attributes `gen0, gen1, gen2`. The `gen0` attribute on this metric maps directly to the Datadog runtime metric `runtime.dotnet.gc.count.gen0`.
=> Add support for OTel .NET runtime metrics

internal/tools/generate-license-file/main.go, pkg/internal/sketchtest/go.mod, pkg/internal/sketchtest/go.sum, pkg/internal/sketchtest/quantile.go, pkg/internal/sketchtest/quantile_test.go, pkg/otlp/metrics/go.mod, pkg/otlp/metrics/go.sum, pkg/otlp/metrics/histograms_test.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/sketches_test.go, pkg/quantile/ddsketch_test.go, pkg/quantile/go.mod, pkg/quantile/go.sum, pkg/quantile/store_test.go, versions.yaml
The first few commits add some missing tests based on coverage:
- Add min/max to tests about histograms
- Add test with empty histogram
- Add test with unsupported combination of options
- Add test for Cols
The last two commits add a new `pkg/internal/sketchtest` module for defining common test helpers for tests in `pkg/quantile` and `pkg/otlp/metrics`. These helpers help define the [quantile function](https://en.wikipedia.org/wiki/Quantile_function) of different common distributions. In particular I added the (truncated) normal and exponential distributions to have more real-world looking tests (since I would expect both of these to be common in the wild). The naming of parameters is based on how they appear on Wikipedia.
I then use this new module to add more tests, notably one on …
=> Add more histogram and exponential histogram tests

.chloggen/mackjmr-deprecate-usePreviewRules.yaml, pkg/otlp/attributes/azure/azure.go, pkg/otlp/attributes/azure/azure_test.go, pkg/otlp/attributes/ec2/ec2.go, pkg/otlp/attributes/ec2/ec2_test.go, pkg/otlp/attributes/gcp/gcp.go, pkg/otlp/attributes/gcp/gcp_test.go, pkg/otlp/attributes/source.go, pkg/otlp/attributes/source_test.go
This PR marks the exported functions which use the `usePreviewRules` parameter as deprecated, and adds new replacement functions without parameter `usePreviewRules`.
This is the first step to graduate the `exporter.datadog.hostname.preview` feature gate to stable.
Once this change is released, the next steps are:
- Marking the `exporter.datadog.hostname.preview` feature gate as stable (cannot remove it completely yet -- see [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/7044)) and replace deprecated functions calls by new function calls in `opentelemetry-collector-contrib` and `datadog-agent`.
- Remove deprecated functions and codepaths which use preview rules in `opentelemetry-mapping-go`.
- [optional] Rename functions to original name following approach …
=> [pkg/otlp/attributes] Deprecate and replace functions which have usePreviewRules parameter.

.chloggen/mx-psi_min-max-metrics1.yaml, .chloggen/mx-psi_min-max-metrics2.yaml, pkg/otlp/metrics/config.go, pkg/otlp/metrics/exponential_histograms_translator.go, pkg/otlp/metrics/histograms_test.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/mixed_metrics_test.go, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-delta_counters-cs.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-delta_dist-cs.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-delta_nobuckets-cs.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-exponential_all.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-exponential_cs-both-tags.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-exponential_cs-ilmd-tags.json, pkg/otlp/metrics/testdata/datadogdata/histogram/simple-exponential_cs.json
- Send min and max histogram aggregations for delta histograms and delta exponential histograms when using the `metrics.WithHistogramAggregations` option.
- Deprecate `metrics.WithSumCountMetrics` in favor of `metrics.WithHistogramAggregations`
Allow backend to leverage these values when available.
=> [pkg/otlp/metrics] Send min and max metrics for delta histograms; rename option to send aggregations

pkg/otlp/metrics/config.go, pkg/otlp/metrics/metrics_translator.go
This PR deprecates and remove usage of WithPreviewHostnameFromAttributes by making the hostname preview always enabled. Once the changes in this PR are released, usage of this function in the [agent](https://github.com/DataDog/datadog-agent/blob/7.42.x/pkg/otlp/internal/serializerexporter/exporter.go#L94) and [collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.75.0/exporter/datadogexporter/metrics_exporter.go#L94) will be removed.
https://datadoghq.atlassian.net/browse/OTEL-231
=> [pkg/otlp/metrics] Deprecate and remove usage of WithPreviewHostnameFromAttributes

.github/workflows/test.yaml, Makefile, internal/tools/go.mod
Add CI check to check for breaking changes. You can see it in action in #47. If a breaking change happens, the CI check will fal. The CI check can be skipped by adding the `breaking-change` label.
Ensure that we catch breaking changes automatically and we follow the deprecation process (see #1)
=> Add apidiff CI check

.github/workflows/test.yaml
Currently, the breaking changes workflow is failing for push events ([example](https://github.com/DataDog/opentelemetry-mapping-go/actions/runs/4678758871)).
This is due to the fact that `github.head_ref` is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target` (see [doc](https://docs.github.com/en/actions/learn-github-actions/contexts#:~:text=GitHub%20GraphQL%20API.-,github.head_ref,-string)).
- link to [push events](https://github.com/DataDog/opentelemetry-mapping-go/actions?query=event%3Apush) ❌
- link to [pull_request events](https://github.com/DataDog/opentelemetry-mapping-go/actions?query=event%3Apull_request) ✅
This PR modifies the breaking changes workflow to only run when the event_name is `pull_request`.
Failing tests …
=> Fix breaking changes workflow

pkg/otlp/metrics/metrics_translator_benchmark_test.go, pkg/otlp/metrics/metrics_translator_test.go
Add benchmark tests for the following cases, both with and without mappings:
- Mapping sum runtime metric without attributes
- Mapping gauge runtime metric with 1 attribute
- Mapping gauge runtime metric with 10 attributes
- Mapping gauge runtime metric with 100 attributes
For a runtime metric without attributes, it seems to take double the amount of time with the runtime metric mapping. As you add more attributes to the runtime metrics, the performance of the runtime metric mapping becomes closer to the performance without the runtime metric mapping.
```
BenchmarkMapSumRuntimeMetric/BenchmarkMapRuntimeMetricsHasMapping-10-10         	   57350	     20915 ns/op
BenchmarkMapSumRuntimeMetric/BenchmarkMapRuntimeMetricsNoMapping-10-10          	  104792	     11669 ns/op …
```
=> Add benchmark tests for runtime metric mappings

pkg/otlp/attributes/attributes.go, pkg/otlp/attributes/attributes_test.go
Add remapping of semantic convention `container.runtime` to Datadog's counterpart `runtime`.
Needed for container metrics dashboard to function correctly. It is one of the global filters.
=> pkg/otlp/attributes: add remapping for container.runtime

.chloggen/stanley.liu_refactor-runtime-metrics-telemetry.yaml, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Renames MapMetrics return struct from `RuntimeMetricsTelemetry` to `Metadata`, renames `LanguageTags` to `Languages`, and removes the `HasRuntimeMetrics` bool because this can be derived from whether `Languages` is empty or not.
Addresses this comment on previous PR: https://github.com/DataDog/opentelemetry-mapping-go/pull/81/files#r1211478541
=> [pkg/otlp/metrics] Refactor MapMetrics return struct

.chloggen/gbbr_remap-metrics.yaml, pkg/otlp/metrics/config.go, pkg/otlp/metrics/metrics_remapping.go, pkg/otlp/metrics/metrics_remapping_test.go, pkg/otlp/metrics/metrics_translator.go
This change adds the processing code for extracting Datadog metrics from container.* and system.* metrics with the intention of centralising this logic to be re-used in the backend intake.
The operation is restricted by the newly added WithRemapping translator configuration option, so that it does not affect the translator's usage as part of the Datadog Agent, where no remapping is necessary because the agent creates the necessary metrics.
Closes #102
=> pkg/otlp/metrics: add remapping code

CHANGELOG.md, LICENSE-3rdparty.csv, internal/tools/go.mod, pkg/internal/sketchtest/go.mod, pkg/otlp/attributes/go.mod, pkg/otlp/logs/go.mod, pkg/otlp/metrics/consumer.go, pkg/otlp/metrics/go.mod, pkg/otlp/metrics/go.sum, pkg/otlp/metrics/metrics_translator_test.go, pkg/otlp/metrics/sketches_test.go, pkg/otlp/metrics/statspayload.go, pkg/otlp/metrics/statspayload_test.go, pkg/otlp/metrics/testhelper_test.go, pkg/quantile/go.mod
This change retracts v0.4.0 and reverts #103.
#103 shouldn't have been released. It is blocking us from updating the contrib collector because pkg/trace in datadog-agent isn't updated with these changes. Furthermore, those changes aren't yet out.
=> Retract v0.4.0

.chloggen/mx-psi_counter-mode.yaml, pkg/otlp/metrics/config.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/mixed_metrics_test.go, pkg/otlp/metrics/testdata/datadogdata/mixed/simple_drop.json, pkg/otlp/metrics/testdata/datadogdata/mixed/simple_keep.json
- [pkg/otlp/metrics] Use NumberMode internally instead of 'SendMonotonic'
- [pkg/otlp/metrics] Add initial value mode to set what to do with the initial value of a cumulative monotonic sum when under the 'cumulative_to_delta' mode. Possible values are the same as in open-telemetry/opentelemetry-collector-contrib/pull/21905.
Relates to #100
=> [pkg/otlp/metrics] Add WithInitialValueMode to metrics translator

.golangci.yml, pkg/inframetadata/go.mod
Fix the depguard failures in https://github.com/DataDog/opentelemetry-mapping-go/actions/runs/5442944976/jobs/9898864233?pr=115.
=> Fix depguard in golangci

pkg/otlp/logs/logs_translator.go, pkg/otlp/logs/logs_translator_test.go
Do not append `otel_source` tag to DDTags. Removed so that datadog-exporter and datadog-agent can each append their own `otel_source` tags.
=> [pkg/otlp/logs] Remove otel_source tag from log translator

pkg/quantile/agent.go
This commit reorders the fields in the Agent struct to require less padding in that type, shrinking it by ~1/2. No change in behavior is intended.
This was discovered while investigating high memory use in the Agent under some circumstances, see SMP-664 and AML-825.
=> [chore] Shrink `Agent` struct from 104 bytes to 56

.chloggen/otel_744_add_resource_attrs_to_log.yaml, pkg/otlp/logs/logs_translator.go, pkg/otlp/logs/logs_translator_test.go
Instead of discarding all resource attributes other than hostname and service, populate "AdditionalProperties" of logs. To avoid overwriting those attributes when marshalling JSON (if they're populated elsewhere), prefix those attributes with "`otel.`"
https://datadoghq.atlassian.net/browse/OTEL-744
=> Add resource attributes to log

.chloggen/stanley.liu_update-jvm-loaded-classes.yaml, pkg/otlp/metrics/metrics_translator_test.go, pkg/otlp/metrics/runtime_metric_mappings.go
Changes mapping for `jvm.loaded_classes` from `process.runtime.jvm.classes.loaded` to `process.runtime.jvm.classes.current_loaded`
#124
=> Fix mapping for `jvm.loaded_classes`

.chloggen/mx-psi_hostmetadata-on-first-sight.yaml, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go, pkg/inframetadata/reporter.go
- Add `Set` method to `Reporter`
- Push host metadata the first time a host is seen or its metadata changes.
=> [pkg/inframetadata] Send payload on changes, add ConsumeHostMetadata

pkg/quantile/pool.go, pkg/quantile/store.go
Reduce allocations in `sparseStore.trimLeft` by pooling the overflow list. This code was identified as a hotspot as part of some agent performance work that I'm doing. (There's a writeup in a notebook [here](https://app.datadoghq.com/notebook/6366141/an-agent-performance-journey-dogstatsd).)
This improves agent's performance in the `uds_dogstatsd_to_api` SMP experiment by around 40%.
=> Pool the overflow list in `sparseStore.trimLeft`

.chloggen/mx-psi_cpu-model.yaml, pkg/inframetadata/gohai/gohai.go, pkg/inframetadata/internal/hostmap/constants.go, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go
Adds support for upcoming CPU resource attributes defined by open-telemetry/semantic-conventions/pull/209.
OpenTelemetry customers have this information available for all hosts.
=> [pkg/inframetadata] Add support for host.cpu attributes

.chloggen/mx-psi_dimensions-change.yaml, pkg/otlp/metrics/dimensions.go, pkg/otlp/metrics/origin.go, pkg/otlp/metrics/testhelper_test.go
Subset of #203 that I want to land first to be able to update the clients.
Right now all metrics will have unset origin product/service/category since this is the zero value.
Support for metrics origin
=> [pkg/otlp/metrics] Initial support for metrics origin

.chloggen/mackjmr_add-support-for-nested-log-attributes.yaml, pkg/otlp/logs/logs_translator.go, pkg/otlp/logs/logs_translator_test.go
This PR adds support for nested log attributes.
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26382
=> OTEL-919: Add support for nested log attributes

.chloggen/mackjmr_remove-unused-rattr-as-tags.yaml, pkg/otlp/metrics/config.go, pkg/otlp/metrics/histograms_test.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/mixed_metrics_test.go
Remove `ResourceAttributesAsTags` from translator config as this gets called directly via metrics exporter config in:
- Agent: https://github.com/DataDog/datadog-agent/blob/main/comp/otelcol/otlp/internal/serializerexporter/factory.go#L60
- DatadogExporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/factory.go#L298
This was flagged in: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29702 and #156.
=> Remove ResourceAttributesAsTags

.chloggen/mx-psi_host-addresses.yaml, pkg/inframetadata/gohai/gohai.go, pkg/inframetadata/internal/hostmap/constants.go, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go
Adds support for `host.ip` and `host.mac` in host metadata
They are useful fields!
=> [pkg/inframetadata] Add support for host.ip and host.mac

.chloggen/mx-psi_rename-to-resource.yaml, pkg/otlp/metrics/go.mod, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/source_test.go
Renames metric to `datadog.otlp_translator.resources.missing_source` as in #222.
This PR is to ensure that we don't have to make breaking changes on the metric while the refactor proposed in #222 is happening.
=> Rename metric to datadog.otlp_translator.resources.missing_source

.chloggen/host-tags-auto.yaml, .chloggen/mx-psi_host-tags.yaml, LICENSE-3rdparty.csv, pkg/inframetadata/internal/hostmap/errors.go, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go, pkg/inframetadata/internal/hostmap/tags.go
- Resource attributes prefixed by `datadog.host.tag.` are now added as host tags for the host associated with the resource.
- Resource attributes for deployment environment and cluster name are now automatically added as host tags for the host associated with the resource.
Edge cases:
- If the type of a `datadog.host.tag.` prefixed attribute is not string, en error is raised
- If a `datadog.host.tag.` attribute has an empty string as a value, an error is raised
- Host tags are not updated per-tag but rather as a whole. For example, if a payload has `datadog.host.tag.foo -> bar` and `datadog.host.tag.baz -> qux` as resource attributes, and the next one only has `datadog.host.tag.foo -> bar`, the final payload after these transformations will only have `foo:bar` and **NOT** `baz:qux`. This …
=> [pkg/inframetadata] Add support for host tags

.chloggen/mx-psi_empty-histograms.yaml, pkg/otlp/metrics/histograms_test.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/testdata/datadogdata/histogram/empty-delta-no-min-max.json, pkg/otlp/metrics/testdata/datadogdata/histogram/empty-delta-with-min-max.json, pkg/otlp/metrics/testdata/datadogdata/histogram/single-bucket-delta-no-min-max.json, pkg/otlp/metrics/testdata/datadogdata/histogram/single-bucket-delta-with-min-max.json, pkg/otlp/metrics/testdata/otlpdata/histogram/empty-delta-no-min-max.json, pkg/otlp/metrics/testdata/otlpdata/histogram/empty-delta-with-min-max.json, pkg/otlp/metrics/testdata/otlpdata/histogram/single-bucket-delta-no-min-max.json, pkg/otlp/metrics/testdata/otlpdata/histogram/single-bucket-delta-with-min-max.json
- [pkg/otlp/metrics] Refactor histogram loop to use slice
- [pkg/otlp/metrics] Add a single bucket for empty histograms
Fixes #252 by adding buckets representing the information conveyed by min, max, and count in the case a histogram is empty.
=> [pkg/otlp/metrics][OTEL-1652] Support empty histograms

.chloggen/stanley.liu_add-stable-java-runtime-metrics.yaml, pkg/otlp/metrics/runtime_metric_mappings.go
Adds runtime metric mappings for new stable JVM metrics added in [opentelemetry-java-instrumentation v2.0.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0).
Docs for new runtime metrics: https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/
Tested locally with OTel Java app instrumented with v2.0.0 and verified that metrics are mapping as intended.
=> Add stable Java runtime metric mappings

.chloggen/mx-psi_availability-zone.yaml, pkg/inframetadata/internal/hostmap/hostmap_test.go, pkg/inframetadata/internal/hostmap/tags.go
Adds `cloud.region`, `cloud.availability_zone` and `cloud.provider` as host tags
=> [pkg/inframetadata] Add cloud conventions as host tags to host metadata

.chloggen/mx-psi_improve-warning.yaml, pkg/inframetadata/reporter.go
Uses `AsRaw` for printing resource attributes and links reference page on mapping OTLP resource attributes to hostnames.
`pcommon.Map` doesn't have a very sensible formatting. With the following sample program:
```go
package main
import (
"go.opentelemetry.io/collector/pdata/pcommon"
"go.uber.org/zap"
)
func main() {
logger := zap.NewExample() // or NewProduction, or NewDevelopment
defer logger.Sync()
m := pcommon.NewMap()
if err := m.FromRaw(map[string]any{"key": "value"}); err != nil {
panic(err)
}
logger.Info("Testing logging of pcommon.Map", zap.Any("map", m), zap.Any("raw map", m.AsRaw()))
}
```
We can see the following output:
```
❯ go run main.go
{"level":"info","msg":"Testing logging of pcommon.Map","map":{},"raw map":{"key":"value"}}
```
Where `map` is shown as empty, when it …
=> [pkg/inframetadata] Improve warning when host-identifying attributes are missing

pkg/otlp/metrics/histograms_test.go, pkg/otlp/metrics/testdata/datadogdata/histogram/static-cumulative_dist-cs.json, pkg/otlp/metrics/testdata/datadogdata/histogram/zero-delta_dist-cs.json, pkg/otlp/metrics/testdata/otlpdata/histogram/static-cumulative.json, pkg/otlp/metrics/testdata/otlpdata/histogram/zero-delta.json
Add tests for histograms that do not have any points in them
This is inconsistent with how we deal with e.g. counters, so we will likely want to change this, but for now this just adds some testing scaffolding
=> [pkg/otlp/metrics] Add tests for empty histograms

.chloggen/mx-psi_more-resilient-host-metadata.yaml, pkg/inframetadata/gohai/gohai.go, pkg/inframetadata/payload/payload.go
Initializes gohai fields on first access to avoid nil pointer dereference
Fixes #306
=> [pkg/inframetadata] Initialize gohai fields on first access

.chloggen/mx-psi_no-recorded-flag.yaml, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Adds support for `NoRecordedValue` flag, meant to represent staleness markers from Prometheus.
If we don't ignore these points, they can mess with our logic for detecting resets in cumulative timeseries
=> [pkg/otlp/metrics] Add support for NoRecordedValue flag

.chloggen/kevinnoel-be_fix-panic-on-invalid-trace-span-ids.yaml, pkg/otlp/logs/transform.go, pkg/otlp/logs/transform_test.go
Fix for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33566
=> Fix panics on invalid sized trace & span IDs

.chloggen/agent-metrics-prefix.yaml, pkg/otlp/metrics/metrics_remapping.go, pkg/otlp/metrics/metrics_remapping_test.go
Add otelcol_ prefix to internal metrics from trace agent
Mitigate a breaking change from upstream
=> [OTEL-2048] Add otelcol_ prefix to internal metrics from trace agent

.chloggen/new-env-conv.yaml, pkg/inframetadata/internal/hostmap/hostmap_test.go, pkg/inframetadata/internal/hostmap/tags.go, pkg/otlp/attributes/attributes.go, pkg/otlp/attributes/attributes_test.go
Map the new OTel semantic convention `deployment.environment.name` to `env`
Support [semconv v1.27.0](https://pkg.go.dev/go.opentelemetry.io/collector/semconv@v0.108.1/v1.27.0)
=> [OTEL-2071] Map deployment.environment.name to env

.chloggen/metrics-prefix.yaml, pkg/otlp/metrics/metrics_remapping.go, pkg/otlp/metrics/metrics_remapping_test.go
Stop prefixing `http_server_duration`, `http_server_request_size` and `http_server_response_size` with `otelcol_`
These metrics can be from SDKs rather than collector. Stop prefixing them to be consistent with https://opentelemetry.io/docs/collector/internal-telemetry/#lists-of-internal-metrics
=> [OTEL-2182] Stop prefixing some HTTP metrics with otelcol

pkg/inframetadata/go.mod, pkg/inframetadata/go.sum, pkg/otlp/attributes/go.mod, pkg/otlp/attributes/go.sum, pkg/otlp/logs/go.mod, pkg/otlp/logs/go.sum, pkg/otlp/metrics/go.mod, pkg/otlp/metrics/go.sum
Reverts DataDog/opentelemetry-mapping-go#284
breaks main
=> Revert "Bump go.opentelemetry.io/collector/semconv from 0.94.1 to 0.95.0 in /pkg/otlp/attributes"

pkg/otlp/logs/go.mod, pkg/otlp/logs/go.sum, pkg/otlp/logs/transform.go, pkg/otlp/logs/transform_test.go
upgrade datadog-api-client-go version and fix breaking changes
one more step to unblock deps upgrade in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36532
=> [pkg/otlp/logs] upgrade datadog-api-client-go version

.chloggen/fix-metric-origin.yaml, pkg/otlp/metrics/origin.go, pkg/otlp/metrics/origin_test.go, pkg/otlp/metrics/testdata/otlpdata/origin/origin.json
Fix metric origin mappings from OTel collector receiver instrumentation scope
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34586 changed instrumentation scope from `otelcol/abc` to `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/abc`
=> [OTEL-2361] Fix metric origin mappings from OTel collector receiver instrumentation scope

.chloggen/go-version.yaml, .github/workflows/changelog.yml, .github/workflows/test.yaml, Makefile, internal/tools/go.mod, pkg/inframetadata/go.mod, pkg/inframetadata/gohai/internal/gohaitest/go.mod, pkg/internal/sketchtest/go.mod, pkg/otlp/attributes/go.mod, pkg/otlp/logs/go.mod, pkg/otlp/metrics/go.mod, pkg/quantile/go.mod
Bump required minimum Go version to 1.23. Add testing for Go 1.24, drop testing for Go 1.22.
This is consistent with the versions supported in OTel collector upstream
=> [OTAGENT-295] Bump required minimum Go version to 1.23

.chloggen/jade-guiton-dd_expose-scope-attributes.yaml, pkg/otlp/logs/transform.go, pkg/otlp/logs/transform_test.go, pkg/otlp/logs/translator.go, pkg/otlp/metrics/internal/instrumentationscope/metadata.go, pkg/otlp/metrics/internal/instrumentationscope/metadata_test.go
Adds support for OTel instrumentation scope attributes in `pkg/otlp/logs` and `pkg/otlp/metrics`, by converting them to log attributes and metric tags. In the latter case, this is locked behind the `WithInstrumentationScopeMetadataAsTags` option, which corresponds to the `instrumentation_scope_metadata_as_tags` setting in the Datadog exporter (but currently nothing in the serializerexporter, I will fix that in a separate PR).
Since last week's release, the OTel Collector has a feature gate which enables injecting scope attributes in its internal telemetry to clearly identify which Collector component emitted it. This makes it important for Datadog to be able to read and display these attributes to the user.
I added test cases to both parts of the code to validate the basic translation …
=> [OTEL-2506] Convert OTel instrumentation scope attributes to log attributes / metric tags

.chloggen/mackjmr_send-host-metadata-new-host.yaml, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go
This fixes a bug when host meta was not sent for new hosts, which means if the host never changed, the host meta would never be sent.
=> Send hostmap on new host

.chloggen/jade-guiton-dd_fix-cumul-to-delta-initial-value.yaml, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Because Datadog does not currently have a concept of cumulative count metrics, we perform cumulative-to-delta conversion in the metrics translator when consuming a monotonic cumulative sum metric. (In the non-monotonic cumulative case, we output a gauge instead). This involves storing the latest value of each metric series, and when receiving a new point, emitting the difference with the previous value.
This however begs the question of how to deal with the first point we receive from a given metric series, since in that scenario we don't have a previous value to compare against. If this is the very first point of the series, then the previous value is implicitly zero, and we can pass through the value as a valid delta. If it isn't, because the translator did not receive previous points …
=> [OTEL-2649] Fix cumulative-to-delta conversion to avoid spikes on translator restart

.chloggen/mackjmr_support-host-aliases.yaml, pkg/inframetadata/internal/hostmap/hostmap.go, pkg/inframetadata/internal/hostmap/hostmap_test.go, pkg/inframetadata/internal/hostmap/tags.go, pkg/inframetadata/internal/hostmap/tags_test.go
This PR adds support for host aliases. Users can now set host aliases by setting resource attribute `datadog.host.use_as_metadata` to true and `datadog.host.aliases` as a slice of host aliases.
=> Add support for host aliases

pkg/quantile/summary/summary_test.go
This PR decreases the number of iterations of the `TestSummary/InsertN` test in `pkg/quantile/summary/summary_test.go` from 1000 to 20.
This test compares the result of calling `Summary.Insert` multiple times versus calling `Summary.InsertN` once. Even if the logic is mathematically correct, due to floating-point imprecision, this can give slightly different results for the sum, and especially for the average, because of the formula that's currently used. And as we repeat the test multiple times, these errors can accumulate past the comparison threshold (256 ULPs).
The current iteration count (1000) causes the test to flake a few percent of the time ([recent example on main CI](https://github.com/DataDog/opentelemetry-mapping-go/actions/runs/15588651484/job/43901727793)), depending on the …
=> Reduce iteration count in TestSummary/InsertN to avoid flakes

.chloggen/mx-psi_do-not-record-host-for-stats-metrics.yaml, pkg/otlp/metrics/metrics_translator.go
Avoids calling `ConsumeHost`/`ConsumeTag` if you only have APM metrics.
While these are metrics they are considered part of the APM product
=> [pkg/otlp/metrics] Do not consume host if you only see APM metrics

.chloggen/mx-psi_delta-interval-infer.yaml, pkg/otlp/metrics/consumer.go, pkg/otlp/metrics/exponential_histograms_translator.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go, pkg/otlp/metrics/sketches_test.go, pkg/otlp/metrics/testhelper_test.go
Explicitly pass `interval` when consuming sketches and timeseries.
The interval type varies between implementations:
- [Zorkian uses `int`](https://pkg.go.dev/gopkg.in/zorkian/go-datadog-api.v2#Metric)
- [datadog-api-client uses `*int64`](https://pkg.go.dev/github.com/DataDog/datadog-api-client-go/v2@v2.19.0/api/datadogV2#MetricSeries)
- [serializer implementation uses `int64`](https://github.com/DataDog/datadog-agent/blob/66a632665c776c6f92397eb4e88f74dc88e143ba/pkg/metrics/series.go#L56)
I have decided to favor the serializer one (`int64`). [`0` is the same as unset](https://github.com/DataDog/datadog-agent/blob/66a632665c776c6f92397eb4e88f74dc88e143ba/comp/otelcol/otlp/components/exporter/serializerexporter/consumer.go#L146).
This allows us to pass interval data if we ever want to …
=> [breaking][pkg/otlp/metrics] Pass interval as part of ConsumeTimeSeries and ConsumeSketch function

.chloggen/mackjmr_support-different-log-attr-types.yaml, pkg/otlp/logs/transform.go, pkg/otlp/logs/transform_test.go
This PR adds support for multiple log attributes value types: `string`, `integer`, `double`, `boolean` (Types were taken from: [Attributes and Aliasing](https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#create-a-new-standard-attribute) )
OTAGENT-432
=> Add support for log attr value int/double/bool types
