versions.yaml
Exclude `generate-license-file` from module sets.
`make prerelease` and `make push-tags` fail otherwise
=> Exclude generate-license-file on versions.yaml

pkg/otlp/attributes/go.mod, pkg/otlp/attributes/go.sum, pkg/otlp/metrics/go.mod, pkg/otlp/metrics/go.sum
Backport DataDog/datadog-agent/pull/15637 to this repository.
Preparing to remove code from Agent codebase.
=> Backport bump to v0.71.0

.chloggen/support-otel-go-runtime-metrics.yaml, .gitignore
Adds .idea/ and .DS_Store to gitignore
=> Add .idea/ and .DS_Store to gitignore

CHANGELOG.md, pkg/otlp/metrics/go.mod, versions.yaml
Update versions.yaml
Update changelog for v0.1.2
Prepare pkgs for version v0.1.2
New release with OTel Go runtime metrics support
=> Prepare for release v0.1.2

internal/scripts/apidiff-compare.sh, internal/scripts/apidiff-generate.sh
Make directory for state apidiff data absolute.
Needed for #42
=> Make apidiff scripts output directory absolute

docs/dev/release.md
Adds command and links that helped last time I made a release.
=> Enhance release instructions.

pkg/otlp/metrics/go.mod, pkg/quantile/go.mod, versions.yaml
Prepare for release v0.2.1:
- Bump version to v0.2.1
- Prepare pkgs for version v0.2.1
=> Prepare for release v0.2.1

pkg/otlp/metrics/go.mod, pkg/quantile/go.mod, versions.yaml
=> Prepare for release v0.2.3

.chloggen/mx-psi_payloads.yaml, internal/tools/generate-license-file/main.go, pkg/inframetadata/go.mod, pkg/inframetadata/gohai/gohai.go, pkg/inframetadata/gohai/processes.go, pkg/inframetadata/payload/payload.go, versions.yaml
Defines the host metadata and gohai payloads. This code is copied over from the Datadog exporter.
Split off from #88
=> [pkg/inframetadata] Create module and define payloads

pkg/otlp/metrics/go.mod, pkg/otlp/metrics/go.sum
Use the up-to-date version of `github.com/DataDog/datadog-agent/pkg/proto`
=> [pkg/otlp/metrics] Fix agent proto dependencies

CHANGELOG.md, pkg/inframetadata/go.mod, pkg/otlp/logs/go.mod, pkg/otlp/metrics/go.mod, pkg/quantile/go.mod, versions.yaml
Remove `otel_source` tag from log translator output
=> Release v0.5.4

.chloggen/mx-psi_map-string-any.yaml, pkg/inframetadata/gohai/gohai.go, pkg/inframetadata/internal/hostmap/hostmap_test.go
Align Gohai types with those returned by `github.com/DataDog/gohai`.
This could lead to a panic when mixing the two.
=> [pkg/inframetadata] Use map[string]any everywhere

pkg/inframetadata/internal/hostmap/hostmap_test.go
=> [chore] Add more tests for cloud.* attributes

pkg/inframetadata/reporter_test.go
Adds an additional test to the changes from https://github.com/DataDog/opentelemetry-mapping-go/pull/276
=> Add cloud provider check in reporter test

.chloggen/dinesh.gurumurthy_make-container-mapping-public.yaml, pkg/otlp/attributes/attributes.go
Makes container Mapping Public
=> Make container mapping public

CHANGELOG.md, versions.yaml
Includes:
- https://github.com/DataDog/opentelemetry-mapping-go/pull/334
- https://github.com/DataDog/opentelemetry-mapping-go/pull/330
=> Prerelease v0.16.1

.github/dependabot.yaml
Groups dependency updates across multiple modules with [the new `directories` configuration key](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories)
Adds three missing modules
Make updates across all modules happen at the same time
=> Group updates on main modules

pkg/otlp/metrics/kafka_mapping.go, pkg/otlp/metrics/metrics_remapping.go, pkg/otlp/metrics/metrics_remapping_test.go, pkg/otlp/metrics/metrics_translator.go, pkg/otlp/metrics/metrics_translator_test.go
Adds a function to renames kafka metrics 
....
=> feat(otlp/metrics): rename kafka metrics

.github/workflows/test.yaml, Makefile
=> test codecov integration

pkg/otlp/metrics/metrics_translator_benchmark_test.go
This PR removes some unused code.
Remove warnings in VSCode.
=> Remove unused code

.gitignore
adds `.vscode/` files to .gitignore
allow local "launch.json" configurations, etc.
=> [chore] add vscode files to gitignore
